name: fedora-build

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
      # 步骤1：拉取代码（宿主Ubuntu上执行）
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤2：构建Fedora镜像（宿主Ubuntu上执行）
      - name: Build hikyuu Fedora image
        run: |
          # 构建镜像（指定Dockerfile路径）
          docker build -f docker/Dockerfile_dev_fedora -t hikyuu-fedora:latest .
          # 验证镜像存在
          docker images | grep hikyuu-fedora

      # 步骤3：在构建好的容器中执行测试（通过docker run手动启动容器）
      - name: Run tests in hikyuu Fedora container
        run: |
          # 用docker run启动容器，挂载当前目录到容器内的/app（确保路径一致）
          # --rm：容器退出后自动删除
          # -v：将宿主的当前目录（$GITHUB_WORKSPACE）挂载到容器的/app
          # -w：指定容器内的工作目录为/app
          docker run --rm \
            -v $GITHUB_WORKSPACE:/app \
            -w /app/hikyuu \
            hikyuu-fedora:latest \
            bash -ic "
              # 在容器内执行的命令
              xmake f -c -k shared --feedback=n -y -vD;
              xmake -b core;
              python hikyuu/test/test.py;
              xmake r small-test;
            "