name: macosx-build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
        arch: [arm64, x86_64]
        kind: [shared]
        python-version: ['3.12', '3.13']

    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-macOS-${{ matrix.arch }}-${{ matrix.kind }}-py${{ matrix.python-version }}
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Cache packages
        id: cache-xmake-macosx
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.xmake
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 3.0.4
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: 'macosx-arm64'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: config
        run: |
          export PYTHONPATH=.
          pip install -r requirements.txt
          xmake f -c -k ${{ matrix.kind }} --serialize=n -y -vD --feedback=n

      - name: build python
        run: |
          xmake -b core   
          
      - name: test python
        run: |
          export PYTHONPATH=.
          python --version
          python3-config --includes
          python -c 'import sys; v = sys.version_info; print(str(v.major)+str(v.minor))'
          python hikyuu/test/test.py
   
      - name: test
        run: |
          xmake r small-test
