name: win-build

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
        arch: [x64] #, arm64]

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Windows-${{ matrix.os }}-${{ matrix.arch }}
        cancel-in-progress: true    
    
    steps:
    - uses: xmake-io/github-action-setup-xmake@v1
    - name: checkout
      run: | 
        git clone https://github.com/fasiondog/hikyuu.git --recursive --depth 1
   
    - name: build
      shell: cmd
      run: |
        cd hikyuu
        xmake f -y
        xmake -b small-test
        xmake r small-test
